server:
  port: 8003
spring:
  application:
    name: mango-admin
  #  boot:
  #    admin:
  #      client:
  #        url: "http://localhost:9000"
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/mango?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: lixinkai
      driver-class-name: com.mysql.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,log4j,config
      # 最大连接数
      max-active: 100
      # 初始化大小
      initial-size: 1
      # 获取连接等待超时时间
      max-wait: 60000
      # 最小连接数
      min-idle: 1
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybestcoding.mango.entity

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
params: count=countSql

# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always