server:
  port: 9000
spring:
  application:
    name: mango-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} # \u6CE8\u518C\u5230consul\u7684\u670D\u52A1\u540D\u79F0
  boot:
    admin:
      discovery:
        ignored-services: consul

# \u5F00\u653E\u5065\u5EB7\u68C0\u67E5\u63A5\u53E3
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always