server:
  port: 8006
spring:
  application:
    name: mango-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#开启熔断器
feign:
  hystrix:
    enabled: true