server:
  port: 8010
spring:
  application:
    name: mango-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: mango-consumer # \u8F6C\u53D1\u5230\u6D88\u8D39\u8005 /ribbon/
    feign:
      path: /feign/**
      serviceId: mango-consumer # \u8F6C\u53D1\u5230\u6D88\u8D39\u8005 /feign/
#  prefix: /v1 # \u6DFB\u52A0\u524D\u7F00